/* Aerovex Plant CFM-style print preview, daily cutting plan, and reports. */
(function(){
const h=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;','"':'&quot;'}[c]));
const n=v=>Math.max(0,Number(v)||0);
const lines=w=>Array.isArray(w.items)&&w.items.length?w.items:[{description:w.description||'',size:w.size||'',cloth:w.cloth||'',width:w.width||'',srl:w.srl||'',qty:n(w.qty),cutQty:n(w.done)}];
const remaining=x=>Math.max(0,n(x.qty)-n(x.cutQty));
const today=()=>new Date().toISOString().slice(0,10);
const css=document.createElement('style');css.textContent=`.axReportBar{display:flex;gap:8px;flex-wrap:wrap;margin:12px 0}.axReportBar button{padding:10px 14px}.axPreview{width:100%;height:min(65vh,780px);border:1px solid #ccd8e1;background:#fff;border-radius:9px}.axReportOptions{display:grid;grid-template-columns:repeat(auto-fit,minmax(175px,1fr));gap:10px}.axReportOptions button{text-align:left;border:1px solid #dbe6ec;border-radius:10px;padding:16px;background:#f4f9fb;color:#184e60;font-weight:700;cursor:pointer}`;document.head.appendChild(css);
let lastHtml='';
function doc(title,body,landscape=true){return '<!doctype html><html><head><meta charset="utf-8"><title>'+h(title)+'</title><style>@page{size:A4 '+(landscape?'landscape':'portrait')+';margin:9mm}*{box-sizing:border-box}body{font:11px Arial,sans-serif;color:#182a35;margin:0}h1{font-size:17px;margin:0 0 4px;color:#155d76}h2{font-size:13px;margin:10px 0}.sub{font-size:10px;color:#596a75;margin-bottom:12px}.head{border-bottom:2px solid #155d76;padding-bottom:8px;margin-bottom:12px}table{width:100%;border-collapse:collapse;table-layout:fixed}th,td{border:1px solid #8696a2;padding:6px 5px;vertical-align:top;overflow-wrap:anywhere}th{background:#eaf3f7;text-align:left}small{color:#667}section.sheet{page-break-after:always;break-after:page}section.sheet:last-child{page-break-after:auto;break-after:auto}.sign{height:28px}.blank{height:30px}.footer{font-size:9px;color:#667;margin-top:8px}@media print{th{print-color-adjust:exact;-webkit-print-color-adjust:exact}}</style></head><body><div class="head"><h1>AEROVEX FILTRATION</h1><div class="sub">Smart Filtration Solutions • '+h(title)+' • Printed '+today()+'</div></div>'+body+'</body></html>'}
function preview(title,html){lastHtml=html;show(title+' — Print Preview','<div class="axReportBar"><button class="primary" id="axDoPrint">🖨 Print / Save as PDF</button><button id="axOpenPreview">Open Full Preview</button><button id="axReportsBack">All Reports</button></div><iframe class="axPreview" title="A4 Print Preview" id="axReportFrame"></iframe><p><small>Print dialog mein Destination: Save as PDF select karein. A4 page layout ready hai.</small></p>');const frame=document.getElementById('axReportFrame');frame.srcdoc=html;document.getElementById('axDoPrint').onclick=()=>{const w=frame.contentWindow;if(w){w.focus();w.print()}};document.getElementById('axOpenPreview').onclick=()=>{const blob=new Blob([html],{type:'text/html'});const url=URL.createObjectURL(blob);const win=window.open(url,'_blank');if(!win)alert('Allow popups for preview');setTimeout(()=>URL.revokeObjectURL(url),60000)};document.getElementById('axReportsBack').onclick=reports}
function plant(){
 const records=db.workOrders.flatMap(w=>lines(w).filter(x=>remaining(x)>0).map(x=>({w,x})));
 if(!records.length)return preview('Daily Plant Cutting Plan',doc('Daily Plant Cutting Plan','<p>No pending cutting orders.</p>'));
 const pages=[];for(let i=0;i<records.length;i+=5){const group=records.slice(i,i+5);pages.push('<section class="sheet"><h2>DAILY PLANT CUTTING PLAN — '+h(today())+' &nbsp; | &nbsp; Page '+(pages.length+1)+'</h2><table><thead><tr><th style="width:10%">Work No / Party</th><th style="width:18%">Description / Size</th><th style="width:12%">Cloth / Width</th><th style="width:7%">Order</th><th style="width:7%">Cut</th><th style="width:7%">Pending</th><th style="width:13%">Available SRL / Alternate</th><th style="width:12%">Actual SRL</th><th style="width:7%">Cut Qty</th><th style="width:7%">Meter</th></tr></thead><tbody>'+group.map(({w,x})=>{let store=db.store.filter(s=>String(s.cloth||s.material||'').trim().toLowerCase()===String(x.cloth||'').trim().toLowerCase()&&(!x.width||String(s.width||'').replace(/[^0-9.]/g,'')===String(x.width).replace(/[^0-9.]/g,''))&&n(s.balance||s.closing)>0).map(s=>h(s.srl||s.serial||s.serialNo||s.srlNo)+' ('+n(s.balance||s.closing)+'m)').join(', ');return '<tr><td rowspan="3"><b>'+h(w.workNo||w.orderNo)+'</b><br>'+h(w.party)+'</td><td rowspan="3">'+h(x.description)+'<br>'+h(x.size)+'</td><td rowspan="3">'+h(x.cloth)+'<br>'+h(x.width)+'</td><td rowspan="3">'+n(x.qty)+'</td><td rowspan="3">'+n(x.cutQty)+'</td><td rowspan="3"><b>'+remaining(x)+'</b></td><td rowspan="3">'+(store||'—')+'</td><td class="blank"></td><td></td><td></td></tr><tr><td class="blank"></td><td></td><td></td></tr><tr><td class="blank"></td><td></td><td></td></tr>'}).join('')+'</tbody></table><div class="footer">Prepared By: __________________ &nbsp; Cutting Person: __________________ &nbsp; Checked By: __________________</div></section>')}
 preview('Daily Plant Cutting Plan',doc('Daily Plant Cutting Plan',pages.join('')))
}
function pending(){const rows=db.workOrders.flatMap(w=>lines(w).filter(x=>remaining(x)>0).map(x=>'<tr><td>'+h(w.workNo||w.orderNo)+'</td><td>'+h(w.party)+'</td><td>'+h(x.description)+'</td><td>'+h(x.size)+'</td><td>'+h(x.cloth)+'</td><td>'+h(x.width)+'</td><td>'+n(x.qty)+'</td><td>'+n(x.cutQty)+'</td><td><b>'+remaining(x)+'</b></td></tr>')).join('');preview('Pending Orders',doc('Pending Orders','<table><tr><th>Work No</th><th>Party</th><th>Product</th><th>Size</th><th>Cloth</th><th>Width</th><th>Order</th><th>Cut</th><th>Pending</th></tr>'+rows+'</table>'))}
function cutting(){const rows=db.cutting.map(x=>'<tr><td>'+h(x.date)+'</td><td>'+h(x.workNo)+'</td><td>'+h(x.description)+'</td><td>'+h(x.cloth)+'</td><td>'+h(x.width)+'</td><td>'+h(x.srl)+'</td><td>'+n(x.qty)+'</td><td>'+n(x.meter)+'</td></tr>').join('');preview('Cutting Register',doc('Cutting Register','<table><tr><th>Date</th><th>Work No</th><th>Product</th><th>Cloth</th><th>Width</th><th>SRL</th><th>Cut Qty</th><th>Meter</th></tr>'+rows+'</table>'))}
function stock(){const rows=db.store.map(x=>'<tr><td>'+h(x.srl||x.serial||x.serialNo||x.srlNo)+'</td><td>'+h(x.cloth||x.material)+'</td><td>'+h(x.width)+'</td><td>'+n(x.opening||x.openingStock)+'</td><td>'+n(x.issue)+'</td><td>'+n(x.balance||x.closing)+'</td></tr>').join('');preview('Store SRL Report',doc('Store SRL Report','<table><tr><th>SRL</th><th>Cloth</th><th>Width</th><th>Opening</th><th>Issue</th><th>Balance</th></tr>'+rows+'</table>'))}
function department(){const rows=db.departmentWork.map(x=>'<tr>'+['date','workNo','person','department','given','done','pending'].map(k=>'<td>'+h(x[k])+'</td>').join('')+'</tr>').join('');preview('Daily Department Work Report',doc('Daily Department Work Report','<table><tr><th>Date</th><th>Work No</th><th>Person</th><th>Department</th><th>Given</th><th>Done</th><th>Pending</th></tr>'+rows+'</table>'))}
function packing(){const rows=db.packing.map(x=>'<tr>'+['date','workNo','party','qty','slipNo','status'].map(k=>'<td>'+h(x[k])+'</td>').join('')+'</tr>').join('');preview('Packing Register',doc('Packing Register','<table><tr><th>Date</th><th>Work No</th><th>Party</th><th>Qty</th><th>Slip No</th><th>Status</th></tr>'+rows+'</table>'))}
const actions=[['Daily Plant Cutting Plan',plant],['Pending Order Print',pending],['Daily Cutting Register',cutting],['Store / SRL Stock Report',stock],['Daily Department Work Report',department],['Packing Register',packing]];
function reports(){show('Plant Sheets • Print Preview • PDF Reports','<p>CFM-style A4 sheets. Preview ke baad Print / Save as PDF.</p><div class="axReportOptions">'+actions.map(([name],i)=>'<button type="button" data-report="'+i+'">🖨 '+h(name)+'</button>').join('')+'</div>');document.querySelectorAll('[data-report]').forEach(b=>b.onclick=()=>actions[Number(b.dataset.report)][1]())}
window.axPlantReports=reports;window.axPlantDailySheet=plant;
const old=openModule;openModule=function(name){if(['Reports','Plant Head Work List','Plant Print','Print Preview','Plant Sheets'].includes(name))return reports();return old(name)};
const nav=document.querySelector('.axCFMNav');if(nav){const b=document.createElement('button');b.textContent='🖨 Plant Sheets / PDF';b.onclick=reports;nav.appendChild(b)}
})();