/* CFM-aligned Aerovex work-order workflow, preserving all existing records. */
(function(){
const E=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;','"':'&quot;'}[c]));
const num=v=>Math.max(0,Number(v)||0);
const items=w=>Array.isArray(w.items)&&w.items.length?w.items:[{description:w.description||w.product||'',size:w.size||'',cloth:w.cloth||'',width:w.width||'',srl:w.srl||'',qty:num(w.qty),cutQty:num(w.done)}];
const pending=x=>Math.max(0,num(x.qty)-num(x.cutQty));
const openSerials=(cloth,width)=>db.store.filter(s=>{const sc=String(s.cloth||s.material||'').trim().toLowerCase(),sw=String(s.width||'').replace(/[^0-9.]/g,'');return num(s.balance||s.closing||s.meter||s.mtr)>0&&(!cloth||sc===cloth.trim().toLowerCase())&&(!width||sw===String(width).replace(/[^0-9.]/g,''))}).map(s=>({serial:s.srl||s.serial||s.serialNo||s.srlNo||'',balance:num(s.balance||s.closing||s.meter||s.mtr)}));
const css=document.createElement('style');css.textContent=`.axWOGrid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:10px}.axWOGrid label{display:flex;flex-direction:column;gap:5px;font-size:12px;font-weight:700}.axWOGrid input,.axWOGrid select{width:100%;min-width:0}.axWOLine{background:#f8fbfd;border:1px solid #dbe7ed;border-radius:12px;padding:12px;margin:10px 0}.axWOActions{display:flex;gap:8px;flex-wrap:wrap;margin:12px 0}.axWOTable{width:100%;border-collapse:collapse;font-size:12px}.axWOTable th,.axWOTable td{padding:9px;border-bottom:1px solid #dce7ee;text-align:left}.axWOCard{padding:16px;margin:12px 0;border:1px solid #dce7ee;border-radius:13px;background:white}.axWOCard h3{margin:0 0 8px}.axWOPending{color:#a35a05;font-weight:800}.axWOTableWrap{overflow:auto}.axWOSrl{font-size:11px;color:#276d7d;margin-top:4px}@media(max-width:700px){.axWOGrid{grid-template-columns:repeat(2,minmax(0,1fr))}.axWOCard{padding:10px}.axWOTable{min-width:700px}}`;document.head.appendChild(css);
function line(x={}){
 const box=document.createElement('div');box.className='axWOLine';
 box.innerHTML='<div class="axWOGrid">'+[['description','Product / Description'],['size','Size / Measurement'],['cloth','Cloth'],['width','Actual Width'],['srl','Preferred SRL'],['qty','Order Qty'],['remark','Item Remark']].map(([k,t])=>'<label>'+t+'<input data-k="'+k+'" '+(k==='qty'?'type="number" min="1" step="1" required':'')+' value="'+E(x[k]||'')+'"></label>').join('')+'</div><div class="axWOSrl"></div><button type="button" class="axRemoveLine">Remove Item</button>';
 box.querySelector('.axRemoveLine').onclick=()=>box.remove();
 const refresh=()=>{const c=box.querySelector('[data-k=cloth]').value,w=box.querySelector('[data-k=width]').value,arr=openSerials(c,w);const hint=box.querySelector('.axWOSrl');hint.textContent=arr.length?'Active Store SRL: '+arr.map(a=>a.serial+' ('+a.balance+' m)').join(' • '):'No matching active SRL in Store';const input=box.querySelector('[data-k=srl]');input.setAttribute('list','axSRL'+Array.from(document.querySelectorAll('.axWOLine')).length);let list=box.querySelector('datalist');if(!list){list=document.createElement('datalist');box.appendChild(list)}list.id=input.getAttribute('list');list.innerHTML=arr.map(a=>'<option value="'+E(a.serial)+'"></option>').join('')};
 ['cloth','width'].forEach(k=>box.querySelector('[data-k='+k+']').addEventListener('input',refresh));document.getElementById('axWOLines').appendChild(box);refresh();
}
function editor(index){
 const existing=index==null?null:db.workOrders[index];const w=existing||{};
 show(existing?'Edit Work Order':'New Work Order — CFM Layout','<form id="axWOForm"><div class="axWOGrid"><label>Work No<input name="workNo" required '+(existing?'readonly':'')+' value="'+E(w.workNo||nextWO())+'"></label><label>Party<input name="party" required value="'+E(w.party||'')+'"></label><label>PO / Reference<input name="po" value="'+E(w.po||'')+'"></label><label>Date<input name="date" type="date" value="'+E(w.date||new Date().toISOString().slice(0,10))+'"></label><label>Priority<select name="priority"><option '+(w.priority==='Normal'?'selected':'')+'>Normal</option><option '+(w.priority==='Urgent'?'selected':'')+'>Urgent</option></select></label><label>Remarks<input name="remark" value="'+E(w.remark||'')+'"></label></div><h3>Items / Cloth / SRL</h3><div id="axWOLines"></div><div class="axWOActions"><button type="button" id="axWOAdd">+ Add Item</button><button class="primary">Save Work Order</button><button type="button" id="axWOBack">Pending Orders</button></div></form>');
 const existingLines=existing?items(existing):[{}];existingLines.forEach(line);document.getElementById('axWOAdd').onclick=()=>line();document.getElementById('axWOBack').onclick=listing;
 document.getElementById('axWOForm').onsubmit=e=>{e.preventDefault();const form=e.currentTarget;const d=Object.fromEntries(new FormData(form));const rows=[...form.querySelectorAll('.axWOLine')].map((el,i)=>{const obj={};el.querySelectorAll('[data-k]').forEach(input=>obj[input.dataset.k]=input.value.trim());obj.qty=num(obj.qty);obj.cutQty=existing?num(existingLines[i]?.cutQty):0;return obj}).filter(x=>x.description&&x.qty>0);
 if(!rows.length)return alert('At least one product and quantity required');
 if(rows.some(x=>x.cutQty>x.qty))return alert('Order Qty cannot be less than already cut quantity');
 if(!existing&&db.workOrders.some(x=>x.workNo===d.workNo))return alert('Work No already exists');
 const record={...w,...d,items:rows,qty:rows.reduce((a,x)=>a+x.qty,0),done:rows.reduce((a,x)=>a+x.cutQty,0),description:rows.map(x=>x.description).join(', '),status:rows.every(x=>pending(x)===0)?'Cut Complete':'Open'};
 if(existing)db.workOrders[index]=record;else db.workOrders.push(record);save();render();listing();
 };
}
function listing(){
 const entries=db.workOrders.map((w,i)=>({w,i}));const total=entries.reduce((n,{w})=>n+items(w).reduce((a,x)=>a+pending(x),0),0);
 show('Work Orders & Pending Cutting — CFM Layout','<div class="axWOActions"><button class="primary" id="axNewWO">+ New Work Order</button><button id="axPrintPending">Print Pending Only</button><button id="axShowAll">Show All / Pending</button></div><p><b>'+entries.length+'</b> Work Orders • <b class="axWOPending">'+total+'</b> Pending Qty</p><div id="axWOResults"></div>');
 document.getElementById('axNewWO').onclick=()=>editor();let all=false;document.getElementById('axShowAll').onclick=()=>{all=!all;draw()};document.getElementById('axPrintPending').onclick=printPending;
 function draw(){document.getElementById('axWOResults').innerHTML=entries.filter(({w})=>all||items(w).some(x=>pending(x)>0)).map(({w,i})=>'<section class="axWOCard"><h3>'+E(w.workNo||w.orderNo||'#'+(i+1))+' — '+E(w.party)+'</h3><div class="axWOActions"><button onclick="axWOEdit('+i+')">Edit</button><span>'+E(w.priority||'Normal')+'</span></div><div class="axWOTableWrap"><table class="axWOTable"><thead><tr><th>Product / Size</th><th>Cloth</th><th>Width</th><th>SRL</th><th>Order</th><th>Cut</th><th>Pending</th><th>Action</th></tr></thead><tbody>'+items(w).map((x,j)=>'<tr><td>'+E(x.description)+'<br><small>'+E(x.size)+'</small></td><td>'+E(x.cloth)+'</td><td>'+E(x.width)+'</td><td>'+E(x.srl)+'</td><td>'+num(x.qty)+'</td><td>'+num(x.cutQty)+'</td><td class="axWOPending">'+pending(x)+'</td><td>'+(pending(x)?'<button onclick="axWOCut('+i+','+j+')">Cut Entry</button>':'Done')+'</td></tr>').join('')+'</tbody></table></div></section>').join('')||'<p>No pending work orders.</p>';}
 draw();
}
window.axWOEdit=editor;
window.axWOCut=(i,j)=>{const w=db.workOrders[i],x=items(w)[j];if(!w||!x)return;const left=pending(x);if(!left)return alert('Cutting complete');
 const q=prompt('Cut Qty (Pending '+left+')',String(left));if(q===null)return;const qty=Number(q);if(!Number.isInteger(qty)||qty<1||qty>left)return alert('Invalid cutting quantity');
 const serials=openSerials(x.cloth,x.width);const srl=prompt('Actual SRL'+(serials.length?' — Active: '+serials.map(a=>a.serial).join(', '):''),x.srl||'');if(srl===null)return;
 const met=prompt('Meter consumed','0');if(met===null)return;const meter=Number(met);if(!Number.isFinite(meter)||meter<0)return alert('Invalid meter');
 if(!Array.isArray(w.items))w.items=items(w);w.items[j].cutQty=num(w.items[j].cutQty)+qty;w.done=w.items.reduce((n,a)=>n+num(a.cutQty),0);w.status=w.items.every(a=>pending(a)===0)?'Cut Complete':'Open';
 db.cutting.push({workNo:w.workNo,description:x.description,size:x.size,cloth:x.cloth,width:x.width,srl,qty,meter,date:new Date().toISOString().slice(0,10)});
 save();render();listing();
};
function printPending(){const rows=db.workOrders.flatMap(w=>items(w).filter(x=>pending(x)>0).map(x=>'<tr><td>'+E(w.workNo)+'</td><td>'+E(w.party)+'</td><td>'+E(x.description)+'</td><td>'+E(x.size)+'</td><td>'+E(x.cloth)+'</td><td>'+E(x.width)+'</td><td>'+num(x.qty)+'</td><td>'+num(x.cutQty)+'</td><td>'+pending(x)+'</td><td></td></tr>')).join('');if(!rows)return alert('No pending items');const win=window.open('','_blank');if(!win)return alert('Allow popups');win.document.write('<!doctype html><html><head><title>Pending Cutting</title><style>@page{size:A4 landscape;margin:10mm}body{font:12px Arial}table{width:100%;border-collapse:collapse}td,th{border:1px solid #777;padding:7px;text-align:left}</style></head><body><h2>AEROVEX FILTRATION — DAILY PENDING CUTTING</h2><table><tr><th>Work No</th><th>Party</th><th>Product</th><th>Size</th><th>Cloth</th><th>Width</th><th>Order</th><th>Cut</th><th>Pending</th><th>Actual SRL</th></tr>'+rows+'</table></body></html>');win.document.close();win.print()}
const old=openModule;openModule=function(name){if(name==='New Work Order'||name==='Work Orders')return editor();if(name==='Pending Orders')return listing();return old(name)};
})();